language: java

jdk:
  - oraclejdk8

os:
  - linux

before_install:
  - wget http://prdownloads.sourceforge.net/findbugs/findbugs-3.0.0.tar.gz?download -O /tmp/findbugs-3.0.0.tar.gz
  - tar -xvf /tmp/findbugs-3.0.0.tar.gz
  - export FINDBUGS_HOME=$PWD/findbugs-3.0.0

script: ant dist 

branches:
  only:
      - master
