language: java

jdk:
  - oraclejdk8

os:
  - linux

before_install:
  - wget http://prdownloads.sourceforge.net/findbugs/findbugs-3.0.0.tar.gz?download -O /tmp/findbugs-3.0.0.tar.gz
  - tar -xvf /tmp/findbugs-3.0.0.tar.gz
  - export FINDBUGS_HOME=$PWD/findbugs-3.0.0
  - wget http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.1.201405082137/jacoco-0.7.1.201405082137.zip -O /tmp/jacoco-0.7.1.201405082137.zip
  - unzip /tmp/jacoco-0.7.1.201405082137.zip -d jacoco-0.7.1.201405082137
  - export JACOCO_HOME=$PWD/jacoco-0.7.1.201405082137

script: ant dist 

after_success:
  - mvn clean test jacoco:report coveralls:jacoco

branches:
  only:
      - master
